services:
  nifi:
    build: .
    image: custom-nifi:1.28
    container_name: nifi-ingesta
    networks:
      - pd-net
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: "admin"
      SINGLE_USER_CREDENTIALS_PASSWORD: "ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB"
      NIFI_WEB_HTTP_PORT: 8443
    ports:
      - 18443:8443
    volumes:
      - ./templates:/opt/nifi/nifi-current/conf/templates
      - ../data:/home/nifi/data
      # - ../hadoop/hadoop-conf-files:/opt/hadoop/conf

networks:
  pd-net:
    external: true
